sudo: required
services:
  - docker

before_install:
  - docker build -t joshanchaudhary/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true joshanchaudhary/docker-react yarn test

  deploy:
    provider: elasticbeanstalk
    region: ""
    app: ""
    env: ""
    bucket_name: ""
    bucket_path: "docker"
    on:
      branch: master
    access_key_id: ""
    secret_access_key: ""
